mock_user_db = [
    {"id": 1, "name": "Ashley Bell", "age": 30, "address": "77548 Brian Isle Suite 522, South Corey, KY 50484", "tags": ["friendly", "designer"]},
    {"id": 2, "name": "Christopher Moore", "age": 67, "address": "418 Webster Mission, Lake Laurabury, AK 65961", "tags": ["retired", "traveler"]},
    {"id": 3, "name": "Dustin Hunt", "age": 14, "address": "5711 Michael Via Apt. 127, Davenportton, IL 16744", "tags": ["student"]},
    {"id": 4, "name": "James Rodriguez", "age": 54, "address": "09763 Harrison Fords, North John, FL 41442", "tags": ["manager"]},
    {"id": 5, "name": "Cory Acosta", "age": 34, "address": "37561 David Gardens, Shermanside, AR 49146", "tags": ["developer", "cool"]},
    {"id": 6, "name": "Katherine Scott", "age": 41, "address": "09807 Charles Stravenue, Brownfurt, ID 52671", "tags": ["artist"]},
    {"id": 7, "name": "David Phillips", "age": 29, "address": "5247 Smith Tunnel, South Keith, OR 27203", "tags": ["nice", "blogger"]},
    {"id": 8, "name": "Nicole Lewis", "age": 85, "address": "4698 Sara Junction, West Daniel, TX 15304", "tags": ["retired"]},
    {"id": 9, "name": "Stephanie Harris", "age": 72, "address": "3995 Emily Estates, Lake Edward, TX 55247", "tags": ["traveler"]},
    {"id": 10, "name": "Jason Garcia", "age": 55, "address": "6589 Luis Pines, East Robert, CA 70822", "tags": ["consultant"]},
    {"id": 11, "name": "Sarah King", "age": 63, "address": "08136 Lopez Point, Garrisonmouth, CA 68140", "tags": ["author"]},
    {"id": 12, "name": "Brian Carter", "age": 21, "address": "3071 Anderson Cliffs, West Jamie, NC 01442", "tags": ["student", "developer"]},
    {"id": 13, "name": "Rachel Turner", "age": 24, "address": "4973 Adams Pines, South William, CO 93114", "tags": ["photographer"]},
    {"id": 14, "name": "Joshua Walker", "age": 39, "address": "4371 Scott Wells, Michaelport, MD 72209", "tags": ["engineer"]},
    {"id": 15, "name": "Melissa Hall", "age": 65, "address": "2652 Ryan Isle, Carlsenburgh, MI 61492", "tags": ["retired"]},
    {"id": 16, "name": "Thomas Young", "age": 56, "address": "06124 Scott River, East Teriport, SD 31560", "tags": ["consultant"]},
    {"id": 17, "name": "Emily Allen", "age": 36, "address": "5670 Samuel Springs, West Elizabeth, MO 45181", "tags": ["teacher", "kind"]},
    {"id": 18, "name": "William Nelson", "age": 70, "address": "2654 Robinson Plains, South Mack, NM 31580", "tags": ["gardener"]},
    {"id": 19, "name": "Laura Adams", "age": 22, "address": "8874 Peterson Hills, North Linda, UT 54109", "tags": ["student"]},
    {"id": 20, "name": "John Hill", "age": 48, "address": "6512 Robertson Plains, East Davidtown, IN 23563", "tags": ["engineer"]},
    {"id": 21, "name": "Matthew Green", "age": 38, "address": "7984 Campbell Crescent, West Heather, NC 48015", "tags": ["nice", "manager"]},
    {"id": 22, "name": "Victoria Baker", "age": 19, "address": "0810 Sarah Brooks, West Michelle, ME 61387", "tags": ["intern", "friendly"]},
    {"id": 23, "name": "Brian Perez", "age": 60, "address": "2171 Walker Track, Helenport, FL 47121", "tags": ["senior consultant"]},
    {"id": 24, "name": "Nancy Mitchell", "age": 57, "address": "9824 Lee Plains, South Barbara, OH 20987", "tags": ["author", "traveler"]},
    {"id": 25, "name": "Kevin Robinson", "age": 80, "address": "4172 Nicole Loop, East Emily, GA 41729", "tags": ["retired"]},
    {"id": 26, "name": "Linda Clark", "age": 42, "address": "6885 William Lake, Kennerston, LA 32382", "tags": ["engineer"]},
    {"id": 27, "name": "Charles Rodriguez", "age": 32, "address": "6942 Claire Fields, Chandlerport, WI 60712", "tags": ["developer"]},
    {"id": 28, "name": "Sandra Scott", "age": 29, "address": "2478 Andrew Extension, New Leslie, NC 81602", "tags": ["teacher", "friendly"]},
    {"id": 29, "name": "Paul Adams", "age": 73, "address": "3423 Jennifer Street, East Philip, VA 59429", "tags": ["retired", "gardener"]},
    {"id": 30, "name": "Kathleen Carter", "age": 44, "address": "07136 Ashley Springs, South Kristin, IL 55672", "tags": ["manager", "traveler"]},
    {"id": 31, "name": "Mark Moore", "age": 61, "address": "7581 Moore Cape, Westonland, VT 28601", "tags": ["senior engineer"]},
    {"id": 32, "name": "Angela Johnson", "age": 29, "address": "9731 Nathaniel Plaza, Corysville, TN 87129", "tags": ["artist"]},
    {"id": 33, "name": "Daniel White", "age": 19, "address": "2045 Kelly Fort, South Regina, KY 71737", "tags": ["student"]},
    {"id": 34, "name": "Elizabeth Young", "age": 33, "address": "2764 Michael Lane, West Jeremyport, DE 22836", "tags": ["teacher", "cool"]},
    {"id": 35, "name": "Deborah Martinez", "age": 71, "address": "3927 Fox Summit, South Nicholasville, IL 25373", "tags": ["gardener"]},
    {"id": 36, "name": "Joseph King", "age": 36, "address": "06135 Daniel Loop, East Jasonport, OK 63956", "tags": ["developer"]},
    {"id": 37, "name": "Christopher Perez", "age": 58, "address": "5432 Anthony Fort, New Jesseport, NJ 57032", "tags": ["consultant"]},
    {"id": 38, "name": "Helen Rodriguez", "age": 33, "address": "2217 Jennifer Park, McDanielview, TX 25165", "tags": ["engineer"]},
    {"id": 39, "name": "Benjamin Brown", "age": 39, "address": "6492 Gonzalez Station, Western Frank, UT 87144", "tags": ["manager"]},
    {"id": 40, "name": "Betty Evans", "age": 55, "address": "4436 Karen Village, East Jasper, PA 47281", "tags": ["author", "traveler"]},
    {"id": 41, "name": "Sharon Walker", "age": 27, "address": "3409 Cook Island, East Ryanborough, TX 14234", "tags": ["artist", "nice"]},
    {"id": 42, "name": "Eric Young", "age": 50, "address": "8123 John Trail, South Davidview, NJ 34094", "tags": ["engineer"]},
    {"id": 43, "name": "Donald Harris", "age": 67, "address": "6021 Betty Fork, North Robert, CO 78328", "tags": ["retired", "gardener"]},
    {"id": 44, "name": "Karen Lewis", "age": 60, "address": "7630 Paula Lodge, North Greg, MO 28843", "tags": ["senior consultant"]},
    {"id": 45, "name": "Cynthia Allen", "age": 32, "address": "7132 Taylor Ville, North Matthew, OR 55732", "tags": ["developer", "cool"]},
    {"id": 46, "name": "Christopher King", "age": 18, "address": "5967 Megan Shoals, West Aidan, OH 51762", "tags": ["student", "blogger"]},
    {"id": 47, "name": "Debbie White", "age": 41, "address": "1186 Mason Drive, East Alexis, NE 30781", "tags": ["manager"]},
    {"id": 48, "name": "Janet Evans", "age": 48, "address": "7038 Ann Avenue, South Marie, OK 79423", "tags": ["teacher"]},
    {"id": 49, "name": "Nancy Harris", "age": 51, "address": "6317 Amanda Grove, East Ryan, TX 25170", "tags": ["consultant"]},
    {"id": 50, "name": "Beverly Turner", "age": 29, "address": "3189 Trevor Way, West Christopher, CO 73854", "tags": ["friendly", "photographer"]}
]

# mock_user_db = [
#     {"id": 1, "name": "Ashley Bell", "age": 30, "address": "77548 Brian Isle Suite 522, South Corey, KY 50484"},
#     {"id": 2, "name": "Christopher Moore", "age": 67, "address": "418 Webster Mission, Lake Laurabury, AK 65961"},
#     {"id": 3, "name": "Dustin Hunt", "age": 14, "address": "5711 Michael Via Apt. 127, Davenportton, IL 16744"},
#     {"id": 4, "name": "James Rodriguez", "age": 54, "address": "09763 Harrison Fords, North John, FL 41442"},
#     {"id": 5, "name": "Cory Acosta", "age": 34, "address": "37561 David Gardens, Shermanside, AR 49146"},
#     {"id": 6, "name": "Katherine Scott", "age": 41, "address": "09807 Charles Stravenue, Brownfurt, ID 52671"},
#     {"id": 7, "name": "David Phillips", "age": 29, "address": "5247 Smith Tunnel, South Keith, OR 27203"},
#     {"id": 8, "name": "Nicole Lewis", "age": 85, "address": "4698 Sara Junction, West Daniel, TX 15304"},
#     {"id": 9, "name": "Stephanie Harris", "age": 72, "address": "3995 Emily Estates, Lake Edward, TX 55247"},
#     {"id": 10, "name": "Jason Garcia", "age": 55, "address": "6589 Luis Pines, East Robert, CA 70822"},
#     {"id": 11, "name": "Sarah King", "age": 63, "address": "08136 Lopez Point, Garrisonmouth, CA 68140"},
#     {"id": 12, "name": "Brian Carter", "age": 21, "address": "3071 Anderson Cliffs, West Jamie, NC 01442"},
#     {"id": 13, "name": "Rachel Turner", "age": 24, "address": "4973 Adams Pines, South William, CO 93114"},
#     {"id": 14, "name": "Joshua Walker", "age": 39, "address": "4371 Scott Wells, Michaelport, MD 72209"},
#     {"id": 15, "name": "Melissa Hall", "age": 65, "address": "2652 Ryan Isle, Carlsenburgh, MI 61492"},
#     {"id": 16, "name": "Thomas Young", "age": 56, "address": "06124 Scott River, East Teriport, SD 31560"},
#     {"id": 17, "name": "Emily Allen", "age": 36, "address": "5670 Samuel Springs, West Elizabeth, MO 45181"},
#     {"id": 18, "name": "William Nelson", "age": 70, "address": "2654 Robinson Plains, South Mack, NM 31580"},
#     {"id": 19, "name": "Laura Adams", "age": 22, "address": "8874 Peterson Hills, North Linda, UT 54109"},
#     {"id": 20, "name": "John Hill", "age": 48, "address": "6512 Robertson Plains, East Davidtown, IN 23563"},
#     {"id": 21, "name": "Matthew Green", "age": 38, "address": "7984 Campbell Crescent, West Heather, NC 48015"},
#     {"id": 22, "name": "Victoria Baker", "age": 19, "address": "0810 Sarah Brooks, West Michelle, ME 61387"},
#     {"id": 23, "name": "Brian Perez", "age": 60, "address": "2171 Walker Track, Helenport, FL 47121"},
#     {"id": 24, "name": "Nancy Mitchell", "age": 57, "address": "9824 Lee Plains, South Barbara, OH 20987"},
#     {"id": 25, "name": "Kevin Robinson", "age": 80, "address": "4172 Nicole Loop, East Emily, GA 41729"},
#     {"id": 26, "name": "Linda Clark", "age": 42, "address": "6885 William Lake, Kennerston, LA 32382"},
#     {"id": 27, "name": "Charles Rodriguez", "age": 32, "address": "6942 Claire Fields, Chandlerport, WI 60712"},
#     {"id": 28, "name": "Sandra Scott", "age": 29, "address": "2478 Andrew Extension, New Leslie, NC 81602"},
#     {"id": 29, "name": "Paul Adams", "age": 73, "address": "3423 Jennifer Street, East Philip, VA 59429"},
#     {"id": 30, "name": "Kathleen Carter", "age": 44, "address": "07136 Ashley Springs, South Kristin, IL 55672"},
#     {"id": 31, "name": "Mark Moore", "age": 61, "address": "7581 Moore Cape, Westonland, VT 28601"},
#     {"id": 32, "name": "Angela Johnson", "age": 29, "address": "9731 Nathaniel Plaza, Corysville, TN 87129"},
#     {"id": 33, "name": "Daniel White", "age": 19, "address": "2045 Kelly Fort, South Regina, KY 71737"},
#     {"id": 34, "name": "Elizabeth Young", "age": 33, "address": "2764 Michael Lane, West Jeremyport, DE 22836"},
#     {"id": 35, "name": "Deborah Martinez", "age": 71, "address": "3927 Fox Summit, South Nicholasville, IL 25373"},
#     {"id": 36, "name": "Joseph King", "age": 36, "address": "06135 Daniel Loop, East Jasonport, OK 63956"},
#     {"id": 37, "name": "Christopher Perez", "age": 58, "address": "5432 Anthony Fort, New Jesseport, NJ 57032"},
#     {"id": 38, "name": "Helen Rodriguez", "age": 33, "address": "2217 Jennifer Park, McDanielview, TX 25165"},
#     {"id": 39, "name": "Benjamin Brown", "age": 39, "address": "6492 Gonzalez Station, Western Frank, UT 87144"},
#     {"id": 40, "name": "Betty Evans", "age": 55, "address": "4436 Karen Village, East Jasper, PA 47281"},
#     {"id": 41, "name": "Sharon Walker", "age": 27, "address": "3409 Cook Island, East Ryanborough, TX 14234"},
#     {"id": 42, "name": "Eric Young", "age": 50, "address": "8123 John Trail, South Davidview, NJ 34094"},
#     {"id": 43, "name": "Donald Harris", "age": 67, "address": "6021 Betty Fork, North Robert, CO 78328"},
#     {"id": 44, "name": "Karen Lewis", "age": 60, "address": "7630 Paula Lodge, North Greg, MO 28843"},
#     {"id": 45, "name": "Cynthia Allen", "age": 32, "address": "7132 Taylor Ville, North Matthew, OR 55732"},
#     {"id": 46, "name": "Christopher King", "age": 18, "address": "5967 Megan Shoals, West Aidan, OH 51762"},
#     {"id": 47, "name": "Debbie White", "age": 41, "address": "1186 Mason Drive, East Alexis, NE 30781"},
#     {"id": 48, "name": "Janet Evans", "age": 48, "address": "7038 Ann Avenue, South Marie, OK 79423"},
#     {"id": 49, "name": "Nancy Harris", "age": 51, "address": "6317 Amanda Grove, East Ryan, TX 25170"},
#     {"id": 50, "name": "Beverly Turner", "age": 29, "address": "3189 Trevor Way, West Christopher, CO 73854"}
# ]



mock_table_config_db = [
    { 
        "table_name": "users",
        "column_configs": [
            {
                "title": "Name",
                "key": "name",
                "type": "string",
                "filterable": False,
                "sortable": True,
                "searchable": True
            },
            {
                "title": "Age",
                "key": "age",
                "type": "heatmap",
                "filterable": False,
                "sortable": True,
                "searchable": False
            },
            {
                "title": "Address",
                "key": "address",
                "type": "string",
                "filterable": True,
                "sortable": False,
                "searchable": False
            },
            {
                "title": "Tags",
                "key": "tags",
                "type": "tags",
                "filterable": False,
                "sortable": False,
                "searchable": False
            }
        ],
        "row_style_rules": [
            {
                "field": 'age',
                "operator": 'gt',
                "value": 50,
                "class_name": 'bg-red-50',
            },
            {
                "field": 'age',
                "operator": 'lt',
                "value": 50,
                "class_name": 'bg-green-50',
            }
        ]
    }
]
